# Welcome to the HelpCommand config.yml
# You can edit values here for the plugin

######################################
# Support
######################################
# Documentation: https://hcdocs.voidem.com/
# Discord server: https://support.voidem.com/
# Discord user: voidem
# Spigot user: VoidemLIVE
# GitHub repository: https://github.com/VoidemLIVE/Help-Command-Plugin
######################################
# Plugin config
######################################

######################################
# Main Help Command
######################################

version: "2.8.4" # DO NOT CHANGE THIS VALUE
updateCheck: true # recommended to keep this value as true

help:
  1:
    - "&5----------"
    - "&b&lServer&d&lName"
    - "&bPage 1: Navigation"
    - "&5----------"
    - "&b/warp &7&l- &r&dTeleport to predefined locations"
    - "&b/home &7&l- &r&dTeleport to your set home location"
    - "&b/tpa &7&l- &r&dRequest to teleport to another player"
    - "&b/tpahere &7&l- &r&dRequest another player to teleport to you"
    - "&5----------"
  2:
    - "&5----------"
    - "&b&lServer&d&lName"
    - "&bPage 2: Utility"
    - "&5----------"
    - "&b/heal &7&l- &r&dRestore your health"
    - "&b/feed &7&l- &r&dSatisfy your hunger"
    - "&b/repair &7&l- &r&dRepair your equipped items"
    - "&b/vote &7&l- &r&dVote for the server"
    - "&5----------"
  3:
    - "&5----------"
    - "&b&lServer&d&lName"
    - "&bPage 3: Interaction"
    - "&5----------"
    - "&b/msg &7&l- &r&dSend a private message to another player"
    - "&b/mute &7&l- &r&dMute a player in the chat"
    - "&b/unmute &7&l- &r&dUnmute a previously muted player"
    - "&b/report &7&l- &r&dReport a player for misconduct"
    - "&5----------"
  4:
    - "&5----------"
    - "&b&lServer&d&lName"
    - "&bPage 4: Management"
    - "&5----------"
    - "&b/ban &7&l- &r&dBan a player from the server"
    - "&b/kick &7&l- &r&dKick a player from the server"
    - "&b/mutechat &7&l- &r&dMute the global chat"
    - "&b/clearinventory &7&l- &r&dClear your inventory"
    - "&5----------"
  5:
    - "&5----------"
    - "&b&lServer&d&lName"
    - "&bPage 5: Fun Commands"
    - "&5----------"
    - "&b/summon &7&l- &r&dSummon a mob"
    - "&b/lightning &7&l- &r&dStrike lightning at a location"
    - "&b/tpall &7&l- &r&dTeleport all players to your location"
    - "&b/fly &7&l- &r&dToggle flying mode"
    - "&5----------"
  6:
    - "&5----------"
    - "&b&lServer&d&lName"
    - "&bPage 6: Miscellaneous"
    - "&5----------"
    - "&b/stats &7&l- &r&dDisplay your player statistics"
    - "&b/afk &7&l- &r&dSet yourself as away from keyboard"
    - "&b/rules &7&l- &r&dDisplay server rules"
    - "&b/reportbug &7&l- &r&dReport a bug to the server administrators"
    - "&5----------"


# It is recommended not to delete these pages and to just use the pagesEnabled list to control which pages are to be available

pagesEnabled: [1,2,3,4,5,6] # sets the pages that can be accessed
#aliases: ["helpnav", "helputil", "helpinteract", "helpmanage", "helpfun", "helpmisc"] # sets the aliases for the help command. REQUIRES FULL SERVER RELOAD/RESTART
######################################
# Enabled Commands
######################################

# Please make sure that this value below is either true or false
helpcmd: true
######################################
# Language
######################################
reload: '&aHelpCommand reloading' # sets message for /hc reload
disabled: '&cThis command is disabled' # sets message for if a command is disabled
noargument: '&cPlease use an argument' # sets message for /hc if no arguments are provided
playersOnly: 'Only players can use this command' # sets message for when a command is run from the console
pageNA: '&cThis page does not exist!' # sets message for if a page doesn't exist

pagePrompt:
  enabled: true
  pageNumberColour: 'GREEN'
  pageTextColour: 'GOLD'
  page: 'Page'
######################################